name: CI/CD Pipeline

on: 
  push:
    branches:
      - main
      - acceptance

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Pyhton
        uses: actions/setup-python@v4
        with:
          python-version:3.12.3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Upload Branch - MinioS3
        env:
          MINIO_HOST: "192.168.27.11"
          MINIO_PORT: "9000"
          ACCESS_KEY: "LtJeM4dfwVxTQMW9aWCB"
          SECRET_KEY: "Is2mlxK6LNSCyGLoDUGW7vYPTu3idgQQKWuMTmke"
        run: |
          python buildimage.py